services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2300411@sit.singaporetech.edu.sg
